### ISSUE TITLE
SERIAL PORT INTERFACE CAUSE ERROR

### ISSUE THREAD

**Issue by siddharthdholu** [digidotcom/xbee-android#13]
Actually, I am using your Xbee3 module via **UART** serial port.

I am getting error and therefore "Use Serial Port Interface" radio option gets disable so i cannot select it.

**Error is as below:**
```java
01-21 17:29:24.338 15870-15870/? E/XBeeConnectActivity: fillSerialPorts() | NoClassDefFoundError
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/serial/SerialPortHandler;
        at com.digi.android.serial.SerialPortManager.<init>(Unknown Source)
        at com.digi.xbee.sample.android.xbeemanager.XBeeConnectActivity.fillSerialPorts(XBeeConnectActivity.java:222)
        at com.digi.xbee.sample.android.xbeemanager.XBeeConnectActivity.onCreate(XBeeConnectActivity.java:126)
        at android.app.Activity.performCreate(Activity.java:6251)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5453)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.serial.SerialPortHandler" on path: DexPathList[[zip file "/data/app/com.digi.xbee.sample.android.xbeemanager-2/base.apk"],nativeLibraryDirectories=[/data/app/com.digi.xbee.sample.android.xbeemanager-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.digi.android.serial.SerialPortManager.<init>(Unknown Source) 
        at com.digi.xbee.sample.android.xbeemanager.XBeeConnectActivity.fillSerialPorts(XBeeConnectActivity.java:222) 
        at com.digi.xbee.sample.android.xbeemanager.XBeeConnectActivity.onCreate(XBeeConnectActivity.java:126) 
        at android.app.Activity.performCreate(Activity.java:6251) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5453) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: android.serial.SerialPortHandler
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 16 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by rubenmoral** [comment]
Hi @siddharthdholu,

In order to use the serial port interface option, you need a Digi Embedded for Android device (ConnectCore® 6 or ConnectCore® 8X). In standard Android distributions (phones, tablets...), you can only use the USB host interface.

Best regards.

**Comment by siddharthdholu** [comment]
> Hi @siddharthdholu,
> 
> In order to use the serial port interface option, you need a Digi Embedded for Android device (ConnectCore® 6 or ConnectCore® 8X). In standard Android distributions (phones, tablets...), you can only use the USB host interface.
> 
> Best regards.

Actaully, my error has app level error, not hardware level. Your example code "xbee_manager_sample" throws error **CLASS NOT FOUND: "android.serial.SerialPortHandler"** during invock your library class **"new SerialPortManager(this)"**

```java
               try {
			SerialPortManager serialPortManager = new SerialPortManager(this);
			serialPorts = serialPortManager.listSerialPorts();
			if (serialPorts == null || serialPorts.length == 0) {
				serialPorts = new String[] {getResources().getString(R.string.no_ports_available)};
				useSerialButton.setEnabled(false);
			}
		} catch (NoClassDefFoundError e) {
			serialPorts = new String[] {getResources().getString(R.string.no_ports_available)};
			useSerialButton.setEnabled(false);
		}
```

  , so if I change harware with your hardware then how this error gets solve?

Give me your email ID for futher communication.

Thanks.

**Comment by rubenmoral** [comment]
Hi @siddharthdholu,

I know, that exception is thrown when the Android distribution where this example is running in does not have the Digi's API for the serial port (only available in the mentioned Digi Embedded devices), that's why the example catches the exception to not break the execution when running it in a phone or tablet.

What Android device are you using and how is your XBee 3 module connected to it?

PS: it's better to talk in this thread instead of through email so that other users with similar issues can find the answer easily.

Best regards.

**Comment by siddharthdholu** [comment]
> Hi @siddharthdholu,
> 
> I know, that exception is thrown when the Android distribution where this example is running in does not have the Digi's API for the serial port (only available in the mentioned Digi Embedded devices), that's why the example catches the exception to not break the execution when running it in a phone or tablet.
> 
> What Android device are you using and how is your XBee 3 module connected to it?
> 
> PS: it's better to talk in this thread instead of through email so that other users with similar issues can find the answer easily.
> 
> Best regards.

Hello @rubenmoral ,

- We currently working with **BananaPi W2** containing **customized rooted Android v6.0.1** os. 

- The **Xbee3** module is connected via **UART** on **W2** board as **coordinator**.

When XBee3 module is connected via USB port there is no such issue, it is working perfect. But when I am trying to communicate **via UART serial port**, I'm facing the problem mentioned before so it is unable to communicate. I don't have any alternative for Bpi W2 so it is not possible to replace our hardware design.

Please help me so that I can connect XBee3 module with my Bpi W2 board via UART serial port.

**Comment by rubenmoral** [comment]
Hi @siddharthdholu,

The standard Android distribution does not have an API to work with serial ports, so Digi created one for its embedded products, but, unfortunately, that code is proprietary. If you want to use our library in your Android platform, you will have to find a serial port library ([RXTX for Android](http://www.v-lad.org/projects/gnu.io.android/), for example) and integrate it in ours. The other alternative is to communicate with the XBee module over USB.

Sorry for the inconvenience.
