### ISSUE TITLE
Unable connect device by serial port

### ISSUE THREAD

**Issue by xiaotuan** [digidotcom/xbee-android#27]
The following error message is displayed when a serial port is used to connect the device:
FATAL EXCEPTION: Thread-4
                                                                                                    Process: com.digi.xbee.sample.android.xbeemanager, PID: 14513
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/serial/SerialPortHandler;
                                                                                                    	at com.digi.android.serial.SerialPortManager.<init>(Unknown Source:13)
                                                                                                    	at com.digi.xbee.api.android.connection.serial.SerialPortDigiAndroid.open(SerialPortDigiAndroid.java:177)
                                                                                                    	at com.digi.xbee.api.AbstractXBeeDevice.open(AbstractXBeeDevice.java:3109)
                                                                                                    	at com.digi.xbee.api.XBeeDevice.open(XBeeDevice.java:135)
                                                                                                    	at com.digi.xbee.sample.android.xbeemanager.managers.XBeeManager.openConnection(XBeeManager.java:329)
                                                                                                    	at com.digi.xbee.sample.android.xbeemanager.XBeeConnectActivity$4.run(XBeeConnectActivity.java:199)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.serial.SerialPortHandler" on path: DexPathList[[dex file "/data/data/com.digi.xbee.sample.android.xbeemanager/code_cache/.overlay/base.apk/classes2.dex", zip file "/data/app/~~NEbohlZRTc84Hgulhau7jQ==/com.digi.xbee.sample.android.xbeemanager-BdWWHJzsDXviPL_GEic6XA==/base.apk"],nativeLibraryDirectories=[/data/app/~~NEbohlZRTc84Hgulhau7jQ==/com.digi.xbee.sample.android.xbeemanager-BdWWHJzsDXviPL_GEic6XA==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.digi.android.serial.SerialPortManager.<init>(Unknown Source:13) 
                                                                                                    	at com.digi.xbee.api.android.connection.serial.SerialPortDigiAndroid.open(SerialPortDigiAndroid.java:177) 
                                                                                                    	at com.digi.xbee.api.AbstractXBeeDevice.open(AbstractXBeeDevice.java:3109) 
                                                                                                    	at com.digi.xbee.api.XBeeDevice.open(XBeeDevice.java:135) 
                                                                                                    	at com.digi.xbee.sample.android.xbeemanager.managers.XBeeManager.openConnection(XBeeManager.java:329) 
                                                                                                    	at com.digi.xbee.sample.android.xbeemanager.XBeeConnectActivity$4.run(XBeeConnectActivity.java:199) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by rubenmoral** [comment]
What Android device are you running the example on? A smartphone/tablet or a Digi ConnectCore device? If it's not a Digi device, make sure it has USB host support and that you select the **Use Android USB Host Interface** option in the initial page. You can only use the second option if the example is running on a Digi ConnectCore device.

**Comment by xiaotuan** [comment]
I ran the example on my smartphone。Our company uses the serial port (TX, RX) interface to connect your company's module to the mobile phone, and then uses the xbeeManager.createXBeeDevice(serialPortSpinner.getSelectedItem().toString(), baudRate); method in your company's xbee_manager_sample sample program to connect. An error occurs. Does your company's SDK support serial port and module communication?

**Comment by rubenmoral** [comment]
If you are running the example on a smartphone, you can't use the `createXBeeDevice(port, baudRate)` method of the `XBeeManager` class. That method uses the [Digi Android Serial API](https://www.digi.com/resources/documentation/digidocs/embedded/android/dea11/cc8x/android_r_apix-serial), which is only available in Digi Embedded for Android distributions. That's why you get the exception mentioned in your first post.

In standard Android distributions, you must use the `createXBeeDevice(baudRate)` or `createXBeeDevice(baudRate, usbDevice)` methods, which use the Android USB host API.
