### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by niccellular** [digidotcom/xbee-android#30]
xbee-android-library version 1.0.0 

https://github.com/digidotcom/xbee-android/blob/d9d8760797cab127e34d5e4c9ee4569fb6d75926/xbee_android_library/src/main/java/com/digi/xbee/api/android/connection/usb/AndroidUSBInterface.java#L238

The last parameter in the `getBroadcast` call should be `PendingIntent.FLAG_IMMUTABLE `

See here
https://developer.android.com/reference/android/app/PendingIntent#FLAG_IMMUTABLE

Crashing callstack on Android 14
```
XBeeDevice              com..app.civ                  I  com.digi.xbee.api.android.connection.usb.AndroidUSBInterface@21a28eeOpening the connection interface...
AndroidUSBInterface     com..app.civ                  I  USB XBee Android device found: /dev/bus/usb/001/003
System.err              com..app.civ                  W  java.lang.IllegalArgumentException: com..app.civ: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
System.err              com..app.civ                  W  Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
System.err              com..app.civ                  W  	at android.app.PendingIntent.checkPendingIntent(PendingIntent.java:450)
System.err              com..app.civ                  W  	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:753)
System.err              com..app.civ                  W  	at android.app.PendingIntent.getBroadcast(PendingIntent.java:740)
System.err              com..app.civ                  W  	at com.digi.xbee.api.android.connection.usb.AndroidUSBInterface.open(AndroidUSBInterface.java:238)
System.err              com..app.civ                  W  	at com.digi.xbee.api.AbstractXBeeDevice.open(AbstractXBeeDevice.java:3109)
System.err              com..app.civ                  W  	at com.digi.xbee.api.XBeeDevice.open(XBeeDevice.java:135)
System.err              com..app.civ                  W  	at com..android..plugin..onStart(.java:73)
System.err              com..app.civ                  W  	at com..plugins.impl.UniversalPluginMapComponent.onCreate(SourceFile:26)
System.err              com..app.civ                  W  	at com..plugins.impl.PluginInjectedMapComponent$1.run(SourceFile:39)
System.err              com..app.civ                  W  	at android.os.Handler.handleCallback(Handler.java:959)
System.err              com..app.civ                  W  	at android.os.Handler.dispatchMessage(Handler.java:100)
System.err              com..app.civ                  W  	at android.os.Looper.loopOnce(Looper.java:232)
System.err              com..app.civ                  W  	at android.os.Looper.loop(Looper.java:317)
System.err              com..app.civ                  W  	at android.app.ActivityThread.main(ActivityThread.java:8501)
System.err              com..app.civ                  W  	at java.lang.reflect.Method.invoke(Native Method)
System.err              com..app.civ                  W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
System.err              com..app.civ                  W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by niccellular** [comment]
I patched this bug and remade the .aar then hit another bug immediately after it. Here https://github.com/digidotcom/xbee-android/blob/d9d8760797cab127e34d5e4c9ee4569fb6d75926/xbee_android_library/src/main/java/com/digi/xbee/api/android/connection/usb/AndroidUSBInterface.java#L240

Basically, since Android 14 broadcast receivers must explicitly declare if they are exported or not. See here: https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

I also patched this bug and remade the .aar

My fixes were pass the FLAG_IMMUTABLE to the `getBroadcast` call https://developer.android.com/reference/android/app/PendingIntent#FLAG_IMMUTABLE

and to pass RECEIVER_EXPORTED to the `registerReceiver` call https://developer.android.com/reference/android/content/Context#RECEIVER_EXPORTED

However, the App still fails to `open` the device with the following exception.

Note my hardware is the XK9X-DMS-0 "Digi XBee SX RF Module Dev Kit, US/CA" using API mode 2 (Escaped) plugged into a Pixel 8 via USB. I used XCTU to write all default settings to the device and only changed it to API mode 2.

```
  [main] INFO com.digi.xbee.api.android.XBeeDevice - com.digi.xbee.api.android.connection.usb.AndroidUSBInterface@584a703Opening the connection interface...
  [main] INFO com.digi.xbee.api.android.connection.usb.AndroidUSBInterface - USB XBee Android device found: /dev/bus/usb/001/002
  [main] INFO com.digi.xbee.api.android.XBeeDevice - com.digi.xbee.api.android.connection.usb.AndroidUSBInterface@584a703Connection interface open.
  [main] ERROR com.digi.xbee.api.android.XBeeDevice - There was a timeout while executing the requested operation.
  com.digi.xbee.api.exceptions.TimeoutException: There was a timeout while executing the requested operation.
  	at com.digi.xbee.api.AbstractXBeeDevice.enterATCommandMode(AbstractXBeeDevice.java:3276)
  	at com.digi.xbee.api.AbstractXBeeDevice.determineOperatingMode(AbstractXBeeDevice.java:3219)
  	at com.digi.xbee.api.AbstractXBeeDevice.open(AbstractXBeeDevice.java:3148)
  	at com.digi.xbee.api.XBeeDevice.open(XBeeDevice.java:135)
  [main] INFO com.digi.xbee.api.android.XBeeDevice - com.digi.xbee.api.android.connection.usb.AndroidUSBInterface@584a703Connection interface closed.
  com.digi.xbee.api.exceptions.InvalidOperatingModeException: Could not determine operating mode.
  	at com.digi.xbee.api.AbstractXBeeDevice.open(AbstractXBeeDevice.java:3153)
  	at com.digi.xbee.api.XBeeDevice.open(XBeeDevice.java:135)
 ```

**Comment by niccellular** [comment]
Here is how I am instantiating the XBee. @rubenmoral any ideas?
```Java
        // Instantiate an XBee Android USB permissions listener.
        AndroidUSBPermissionListener permissionListener = permissionGranted -> {
            if (permissionGranted) {
                System.out.println("User granted USB permission.");
                try {
                    if (!myXBeeDevice.isOpen()) {
                        Log.d(TAG, "Opening XBee device");
                        myXBeeDevice.open();
                    } else
                        Log.d(TAG, "XBee device already opened");

                    if (myXBeeDevice.isOpen()) {
                        Log.d(TAG, "Reading PL parameter");
                        final byte[] plVal = myXBeeDevice.getParameter("PL");
                        Log.d(TAG, "PL value: " + plVal);
                    }
                } catch (XBeeException e) {
                    e.printStackTrace();
                }
            }
            else
                System.out.println("User rejected USB permission.");
        };

        myXBeeDevice = new XBeeDevice(context, 9600, permissionListener);
```

**Comment by niccellular** [comment]
I tried using XCTU to first discover the board in "no-programmable" mode as described in another issue, however this did not fix the issue either.

**Comment by doguhan2222** [comment]
I solved this problem. Change theese part of AndroidUSBInterface.java


```
 if (!usbManager.hasPermission(usbDevice)) {
    mPermissionIntent = PendingIntent.getBroadcast(context, 0, 
        new Intent(ACTION_USB_PERMISSION), 
        PendingIntent.FLAG_IMMUTABLE);
        
    IntentFilter filter = new IntentFilter(ACTION_USB_PERMISSION);
    // Add the RECEIVER_NOT_EXPORTED flag since this is for internal app use only
    context.registerReceiver(mUsbReceiver, filter, Context.RECEIVER_NOT_EXPORTED);
    
    usbManager.requestPermission(usbDevice, mPermissionIntent);
    
    if (permissionListener == null) {
        // This should be called when connecting from a thread different than the UI.
        while (!permissionsReceived) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                // Consider handling interruption
            }
        }
        if (!permissionsGranted) {
            throw new PermissionDeniedException("User didn't grant permissions to access XBee device.");
        }
    } else {
        // Main application is waiting now to the permission receiver listener.
        // We have to exit here, main application should try to reconnect again 
        // when permissions are granted. At this point we do not have permissions yet.
        throw new PermissionDeniedException("User didn't grant permissions to access XBee device.");
    }
} 

```

and 

`		mPermissionIntent = PendingIntent.getBroadcast(context, 0,
					new Intent(ACTION_USB_PERMISSION),
					PendingIntent.FLAG_IMMUTABLE);`

**Comment by doguhan2222** [comment]
Tested on Android 14 . Solved problem for me after these changes

**Comment by niccellular** [comment]
> Tested on Android 14 . Solved problem for me after these changes

Yes this is the same solution I came up with however I am still seeing that the development boards that come with the XK9X-DMS-0 fail to `open()` with the error ` com.digi.xbee.api.exceptions.InvalidOperatingModeException: Could not determine operating mode.`

![image](https://github.com/user-attachments/assets/13abb33b-974b-4793-9f13-6fa12ff56f2b)

**Comment by niccellular** [comment]
> Tested on Android 14 . Solved problem for me after these changes

Can you tell me what Digi hardware you are using to test on Android?

**Comment by doguhan2222** [comment]
Im using XBEE3-24Z8CM-J Custom dongle with Type-c.

**Comment by niccellular** [comment]
> Im using XBEE3-24Z8CM-J Custom dongle with Type-c.

Thank you, I suspect my problem is just the dev board has some issue in how it init's the xbee radio.

**Comment by doguhan2222** [comment]
https://we.tl/t-wvBgPRoGSh 

its my xctu profile for my dongle.Im using as a Coordinator.

**Comment by doguhan2222** [comment]
I hope you can solve the problem. Because solving the problems was really difficult for me . Just i tried everything

**Comment by doguhan2222** [comment]
> > Im using XBEE3-24Z8CM-J Custom dongle with Type-c.
> 
> Thank you, I suspect my problem is just the dev board has some issue in how it init's the xbee radio.

i think the main problem is XCTU settings for you. Maybe , role maybe baud rate idk.But im using 802.15.4 and coordinator role for my dongle

**Comment by niccellular** [comment]
> > > Im using XBEE3-24Z8CM-J Custom dongle with Type-c.
> > 
> > 
> > Thank you, I suspect my problem is just the dev board has some issue in how it init's the xbee radio.
> 
> i think the main problem is XCTU settings for you. Maybe , role maybe baud rate idk.But im using 802.15.4 and coordinator role for my dongle

The dev boards work on linux/windows with the xbee-python library its just on Android I have the problem.

**Comment by niccellular** [comment]
The fix for me was to update the interface index when calling getInterface() inside `startUSBConnection`
